export { Hero } from './hero'
export { Trust } from './trust'
export { HowItWorks } from './how-it-works'
export { Features } from './features'
export { Security } from './security'
export { Pricing } from './pricing'
export { Testimonials } from './testimonials'
export { FAQ } from './faq'
